### ISSUE TITLE
Image Storage Solution

### ISSUE THREAD

**Issue by BorhanSaflo** [uwindsorcss/css-site#44]
We need to find a solution for storing images to be displayed in our gallery. We should explore third-party options for image uploading and storage, such as an S3 bucket service, or consider hosting an S3-compatible solution on our own server.

**Comment by SyndicateGit** [comment]
We should discuss the solutions available. 

AWS S3 bucket:
Does CSS have an aws account for S3 buckets? 
Pricing: First 50 TB / Month, $0.023 per GB.
$0.0004 per 1000 get requests.

Cloudinary:
Free up to 25GB storage or 25GB monthly viewing bandwidth.
Not worth it outside free tier since it's $89/month and they're basically hooked up to an S3 bucket.
At past 25GB S3 is more worth.

Postgress Blobs:
Slower storage and retrieval than object storage solutions like S3 buckets. 
Depending on where we host the db (if we're hosting on cloud rather than a self dedicated server at school) it could be more expensive than S3 buckets. 

Things to consider: 
How many GB of images are we handling and thinking of handling in the future?
Do we already have an aws account?
Where are we hosting the postgress db?

**Comment by CalderJohnson** [comment]
@SyndicateGit We currently have an S3 bucket created. I'll message you the credentials. It's a pretty feature heavy platform so if it ends up being overkill we can shift to cloudinary or another solution. The scale will be pretty small (a few posts per month, a few images per post) but cloud storage is a useful thing to set up for many of our potential future endeavors so scalability would be ideal.

**Comment by CalderJohnson** [comment]
We have since begun using Cloudinary as an image storage solution.
